document.addEventListener("DOMContentLoaded", function () {
    const translateButton = document.getElementById("translateButton");
    const inputText = document.getElementById("inputText");
    const outputText = document.getElementById("outputText");

    // Solicitar una traducción al cargar la página
    inputText.focus();

    inputText.addEventListener("input", translateText);

    function translateText() {
        const textToTranslate = inputText.value;
        const translatedText = translate(textToTranslate);
        outputText.textContent = translatedText;
    }

    // Función de traducción
    function translate(text) {
        // Aquí puedes implementar tu lógica de traducción
        // para traducir del español al guaraní
        // Siéntete libre de añadir tus palabras y frases aquí
        // Ejemplo:
        const translationDatabase = {
            "abajo": "yvýpe",
            "abalanzarse": "añemombo hese",
            "abanderado": "poyvi guerahaha",
            "abandonado": "itaperéva",
            "abandonar": "motyre'ỹ",
            "abanicar": "jeipeju",
            "abanico": "pejuha",
            "abaratar": "hepyguejy, mboyvytuha",
            "abarca": "sapatupe, hepy'o",
            "abarcar": "ñañuã, ha'ãmba",
            "abastecer": "hupytyka",
            "abastionar": "mongora",
            "abasto": "hi'upyrãrenda, ñemuha guasu",
            "abatatar": "motĩ, mbochuchu, mongyhyje",
            "abatido": "kangy, tindy, pepo'a",
            "abatir": "motindy, mokangy",
            "abdicar": "kúi, jei, ñemboyke",
            "abdomen": "tye, tyeguy",
            "abecedario": "achegety",
            "abeja": "káva, kavihu'i, kavytã",
            "abejar": "káva raity",
            "abejarrón": "mamanga",
            "abejaruco": "ypekũ, guyra káva",
            "aberración": "jejavy guasu, jepia",
            "aberrar": "jejavy guasu, jejavyvusu",
            "abertura": "juru, jeka, pe'a",
            "abierto": "ojei, ojepe'a",
            "abigarrado": "mbatara, ipararáva, pititĩ",
            "abigeato": "mymba monda",
            "abigeo": "mymba mondaha",
            "abintestato": "potapaha'ỹre, techagihápe",
            "abismar": "mbopypuku, jepy'amongeta",
            "abismo": "yvykua pypuku, itakua hugua'ỹva",
            "ablandar": "mohu'ũ, mbyaruru",
            "ablución": "johéi, ánga ñemopotĩ",
            "abobado": "ijurujáiva, itavyraíva",
            "abobar": "mbojurujái, mbohekotavy, mbotavyrai",
            "abochornado": "otĩva, ovapytãmbáva",
            "abochornar": "motĩ, mbohovapytã",
            "abofeteador": "oporohovapetéva",
            "abofetear": "hovapete, hovanupã",
            "abogado": "mo'ãhára",
            "abogar": "jerure mávare, ñe'ẽ máva rehehápe",
            "abolengo": "ypykuéra poravopyréva, ñemoñarenguéra",
            "abolición": "jeipe'a, ñembogue",
            "abolir": "pe'a, mbogue, hejarei",
            "abollado": "pyko'ẽ, pygua, apeno",
            "abolladura": "pyko'ẽ, kandu",
            "abollar": "mbopygua, moakandu, mopyko'ẽ",
            "abombar": "mboapysakuamboty, moakãtavy, mboapysaryapu",
            "abominar": "cha'e'ỹ, py'aro",
            "abonar": "yvymboavevo, hepyme'ẽ, momora",
            "abono": "yvymoporãha, yvymboavevoha, jehorã",
            "aborigen": "ypykue",
            "aborrecer": "hayhu'ỹ, hayhupe'a, hechase'ỹ",
            "abortar": "membykua",
            "aborto": "membykua, membykuare",
            "abrazar": "añuã, añuvã",
            "abrevar": "mboy'u",
            "abreviar": "mombykypyre, mbykypyre",
            "abridor": "pe'aha, hekyiha, jaipe'aha",
            "abrigar": "jaho'i, ñuvã",
            "abrigo": "aoaku, ahoja",
            "abrir": "pe'a",
            "abrochar": "mboty, movotõ",
            "abrojo": "ñuatĩ'i",
            "abroquelar": "ñemo'ã",
            "abrumar": "momba'apo asy, mbojepy'apy",
            "absoluto": "katuete, pu'akapavẽ",
            "absolver": "jora, mbogue",
            "abstenerse": "jejoko",
            "abstinencia": "japo'ỹ, jejoko",
            "absurdo": "ñe'ẽrei, ha'e'ỹva",
            "abuela": "jarýi, machu",
            "abuelo": "taita, taitachu, tuvaru",
            "abuenar": "moñyrõ, mbopochypoi",
            "abultado": "kandu, chivu",
            "abundancia": "teta",
            "aburrido": "kaigue, kuerái",
            "aburrir": "mbokaigue, monguerái, mbyaju",
            "abusar": "poruvai, momarã, ñemombarete",
            "abuso": "poruvai",
            "acá": "ko'ápe, ápe",
            "acabado": "opáma, oĩmbáma, oikopáma",
            "acabar": "japopa, momba",
            "acacia": "chivato guasu",
            "acaecer": "jehu, ko",
            "acalorado": "mbyry'ái, pireaku, rugueraku",
            "acallar": "mokirirĩ",
            "acampar": "pyta, jepyta",
            "acariciar": "mochichĩ, mokunu'ũ, japichy",
            "acarrear": "roja, raha",
            "acaso": "ikatu, herungua",
            "acatar": "ñakãity, ñe'ẽrendu, mboaje",
            "acceder": "neĩ, moneĩ",
            "accesible": "jakuaaha, neiséva",
            "acceso": "ja, jeja",
            "accesorio": "joapy, temirũ, juapyha",
            "accidente": "ha'arõ'ỹva",
            "acechar": "ma'ẽ ñemi, apera'arõ, moñehã",
            "acefalía": "iñakã'ỹva",
            "acéfalo": "hendot'ỹva, naiñakãiva",
            "aceitar": "moñandy",
            "aceite": "ñandyry, ñandy",
            "acelerado": "puatarara",
            "acelerador": "mbopya'eha",
            "acelerar": "mbopya'e, moagẽ",
            "acento": "muanduhe",
            "aceptar": "nei, monei, mboaje",
            "acero": "kuarepotiete",
            "acertijo": "kuaara'ã, kuapyrã, porandu asy",
            "aclarar": "mohesakã",
            "acné": "jari'i",
            "acomodar": "mohenda, mombyta",
            "acordar": "momandu'a, mandu'a, ñemoĩ peteĩ ñe'ẽme",
            "acortar": "mombyky, momichĩ, mongarape",
            "acusar": "kuaauka, mombe'u, jurumy'ỹi",
            "achicar": "momichĩ, mbo'i",
            "adagio": "ñe'ẽnga",
            "adalid": "tendota, mburuvicha, sãmbyhyha",
            "adelantar": "motenonde, tenonde",
            "adelgazar": "mbopiru, mopererĩ",
            "además": "avei, kóva rire",
            "adentro": "pype, hyepýpe, kotypýpe",
            "adherir": "mboja, mona",
            "adhesivo": "mbojaha",
            "adiestrar": "mbokatupyry, mboha'eve",
            "adiposo": "kyra, iñandýva, ikyráva",
            "administrar": "ñangareko",
            "admirar": "momora, hacharamo, mbojurujái",
            "admitir": "moinge",
            "adolescente": "mitãrusu",
            "adoptar": "ta'yrangáramo, moinge",
            "adorar": "tupãitũ, ñakãity, jayvy",
            "adormecer": "monge, ñemonge",
            "adornar": "mbojegua, moporã, jeguaka",
            "adquirir": "jogua",
            "adquisición": "mba'epyahu",
            "adrede": "ojaposetégui",
            "adueñarse": "ñemomba'e, ñembojára",
            "adular": "mboaguara, mbojuruhe'ẽ",
            "adulto": "ityarõva, kakuaapámava",
            "adúltero": "oporombovakaratĩva, hembireko mokõiva",
            "adverbio": "ñe'ẽteja",
            "advertencia": "ñemomarandu",
            "advertir": "ñatõi, je'epohýi",
            "aéreo": "arapytu",
            "afable": "horýva, hekororýva, hetia'éva",
            "afamado": "herakuãva",
            "afanar": "mokyre'ỹ",
            "afeitar": "tendyva'o",
            "afeminado": "kuñarekóva",
            "afilar": "haimbe'e",
            "afinar": "mosỹi",
            "afirmar": "moatã, mombarete",
            "afrecho": "rorakue, kurukue",
            "afrentar": "motĩ, momarã",
            "afuera": "okápe, oka, okára",
            "agachado": "ojayvýva, atuape, karapã",
            "agachar": "mbojayvy, ñakãity, ñembokarape",
            "agalla": "pira hay'o, py'aguasu",
            "agasajado": "ojeguerohorýva",
            "agasajar": "rohory, jopói",
            "agazaparse": "ijaturu, ijatuape",
            "agencia": "tembiapoha, sãmbyhyha renda",
            "agenda": "apopyrã, ijapopyrã",
            "agente": "apoha, ñangarekoha",
            "ágil": "akuã, rari, vevúi",
            "agitación": "juku'a, py'atarova",
            "agitar": "mbokacha, mbovava",
            "aglomeración": "ñembyaty, teta, atyguasu",
            "agobiar": "jopy, py'apy, moangata",
            "agonía": "manombota, jehekyipota, pytuhẽ asy",
            "agonizar": "manombota, pytupapota",
            "agosto": "jasypoapy, virumono'õ",
            "agotar": "mbohypa, mbokaigue",
            "agradar": "mbohory, mbovy'a",
            "agradecer": "aguyjeme'ẽ, hechakuaa, mboaguyje",
            "agrandar": "mbotuicha, mbopyguasu, mongakuaa",
            "agravar": "mbopohýi, mbovaive",
            "agraviar": "moñemyrõ, jahéi, mbopy'avai",
            "agravio": "ñemyrõ, ñemomarã, ñe'ẽmondopyre",
            "agredir": "rairõ, mbuepoti, havirarei",
            "agregar": "mbojoapy, mbojoa, moĩve",
            "agresión": "rairõrei, ñenupã, havirarei",
            "agricultor": "chokokue, kokue rerekua, temitỹha",
            "agricultura": "ñemitỹ, temitỹmby",
            "agridulce": "he'aivaíva, he'ẽmby, he'ẽjopara",
            "agrietar": "jokatiri, tiri",
            "agrio": "hái",
            "agronomía": "ñemitỹrekokuaa, ñemitỹmbo'e",
            "agrupar": "mono'õno'õ, mbyaty, mbyatypa",
            "aguada": "ygua",
            "aguado": "yreikue, ymeme, mbo'ypyre",
            "aguantar": "ñembesu'u, ñemyatã",
            "aguante": "rosã, pytakuaa, jokokuaa",
            "aguar": "mbo'y",
            "aguardar": "ha'arõ",
            "agudo": "hakua",
            "aguijón": "popía",
            "aguja": "ju",
            "agujerear": "mbokua",
            "agujero": "kua, kuára",
            "ahogar": "mbo'yguy, moñapymi, mbopytupa",
            "ahondar": "mbopypuku",
            "ahora": "ág̃a, ko'ág̃a",
            "ahorcado": "jejuvypyre",
            "ahorcar": "juvy, jejuvy",
            "ahorrado": "ñongatupyre, mboherupyre",
            "ahorrar": "ñongatu, mohemby",
            "ahumado": "moatatĩmbyre, apiche",
            "ahumar": "moatatĩ, motimbo, mboapiche",
            "ahuyentar": "mondýi, mongyhyje, mbojei",
            "aire": "yvytu, pytu",
            "airear": "mboyvytu, mboveve, peju",
            "aislar": "moha'eño, moaño, momombyry",
            "ajado": "piru, ñyñýi",
            "ajar": "javykyvai, haru, mbyai",
            "ajetreo": "kane'õ, mokane'õ",
            "ají": "ky'ỹi",
            "ajo": "sevoiry",
            "ajustar": "mbojoja, moñondive",
            "ajusticiado": "jukapyre",
            "ala": "pepo",
            "alabar": "momba'e, momorã, momarangatu",
            "alacena": "tembiporu renda, ñongatuha",
            "alado": "ipepóva, ovevéva",
            "alarde": "ñembokaria'y, tekojejapo",
            "alargar": "mbopuku, pyso",
            "alarmar": "myangekói, mondýi, mbopy'a angata",
            "albergar": "mbohupa, mbokokty, mombyta",
            "alborada": "ko'ẽmbota, ko'ẽju, ko'ẽtĩ",
            "alborotar": "mbopy'atarova, ayvu",
            "alboroto": "ayvu, sununu",
            "álbum": "ta'angaryru",
            "alcahuete": "kurupi",
            "alcalde": "tavaruvicha, tavarerekua",
            "alcance": "hupyty",
            "alcancía": "viruryru, viruñongatuha",
            "alcanzar": "hupyty",
            "alcoba": "keha, jekeha",
            "aldea": "tava'i, ogaaty",
            "aleatorio": "jerére, ojehureíva",
            "aledaño": "jerére, apyrapegua",
            "alegar": "kuaauka, techauka",
            "alegrar": "mbojhory, rohory",
            "alegre": "hory, rory, vy'a",
            "alegría": "tory, vy'a",
            "alejar": "momombyry",
            "alentar": "mokyre'ỹ, mbohetia'e, mbopy'aguasu",
            "algodón": "mandyju",
            "algodonal": "mandyjuty",
            "alma": "ánga, ã, angue",
            "almacenar": "ñongatu",
            "almanaque": "ararechaukaha, ararysyikue, arambo'eha",
            "almidón": "aramirõ",
            "almohada": "aramboha, akãngyta",
            "almuerzo": "karu, jekaru",
            "alquilar": "poruka, poru",
            "alterar": "myangakói, haru, mbopy'atarova",
            "alternar": "mbojopyru, ñomyengovia, pyru",
            "altura": "yvate, puku",
            "alumbrar": "hesape, myendy, myesakã",
            "alumno": "temimbo'e",
            "alzar": "hupi, mopu'ã",
            "amable": "hory, horýva",
            "amado": "ojehayhúva",
            "amagar": "ha'anga, ha'ãse",
            "amamantar": "mokambu",
            "amanecer": "ko'ẽ, ko'ẽtĩ, ko'ẽju",
            "amansar": "momymba, mbopochypoi, moñarõjera",
            "amante": "hayhuha",
            "amar": "hayhu",
            "amargar": "mboro, mbopy'aro",
            "amargo": "ro, mba'ero",
            "amarillo": "sa'yju",
            "amarrar": "mosã, ñapytĩ, jokua",
            "amasar": "sova, mbojehe'a",
            "ambicionar": "pota, taryrýi",
            "ambicioso": "oipotapáva, taryrýi",
            "ambiente": "arapytu, tekoha",
            "amén": "taupéicha",
            "amigo": "angirũ",
            "amistad": "hayhu, jahayhu",
            "amnistía": "ñerõ, ñemyrõpoi",
            "amontonar": "mbojoa, mboaty",
            "amor": "tembiayhu, mborayhu",
            "ampliar": "mbotuicha, mbopy, mbope",
            "ampolla": "apiru'a",
            "amputar": "ñapĩ, kytĩ, jyva'o",
            "amueblar": "mohembiporu",
            "analfabeto": "tavy, omoñe'ẽ'ỹva",
            "analizar": "ñamindu'u, py'amongeta",
            "ancho": "pe, py",
            "anchura": "pekue, pykue",
            "anciano": "karai tuja, itujáva",
            "andar": "guata",
            "andrajo": "aokue, aotuja",
            "anécdota": "ñemombe'u'i",
            "anemia": "tuguy'i, tuguykangy, tesa'yju",
            "anestesiar": "moandu'ỹ, andumbogue, monge",
            "anexar": "mbojoapy, mbojoaju",
            "ángel": "yvapóra, yvagapóra",
            "angina": "hay'orasy",
            "angosto": "po'i, pa'ũ'i, py'i",
            "anguila": "mbusu",
            "ángulo": "takamby",
            "angustiar": "py'apy, moangata, mbojepy'apy",
            "anhelar": "potaite, py'aho, rekosete",
            "anidar": "jehaitypo, jehupapo",
            "anillo": "kuãirũ",
            "ánima": "ãngue, ánga, angue",
            "animado": "tetemỹi, kyre'ỹ, tetia'e",
            "animal": "tymba, mymba",
            "animar": "mokyre'ỹ, mborari, mbohetia'e",
            "aniquilar": "hekope'a, mbopaha",
            "ano": "tevi, tevikua",
            "anoche": "angepyhare",
            "ansiar": "potaiterei, hi'ãva",
            "anteojo": "tesairũ, tesajo'a",
            "antepasado": "ypykue",
            "anteponer": "motenonde, henonde'a",
            "anterior": "tenondegua, mboyve, mboyvegua",
            "antojo": "tembipota, andugua'u",
            "anular": "mboje'o, momba'eve",
            "anunciar": "momarandu, kuaauka, mombe'u",
            "apaciguar": "mbopy'aguapy, mbopochyjera",
            "apagar": "mbogue",
            "apalear": "nupã, mbyepoti",
            "aparecer": "jehecha, jekuaa, ñapysẽ",
            "apartar": "moha'eño, mboyke, momombyry",
            "apellido": "terajuapy",
            "apertura": "jepe'a, ñepyrũ",
            "apetito": "vare'a, ñembyahýi, mbaepota",
            "aplanar": "mbope, mbojoja",
            "aplastar": "mbojchipe, mbope",
            "aplaudir": "jepopete, guerohory",
            "aplazar": "mbopuku, mbotapykue, mboare",
            "apodo": "hero, jehero",
            "aportar": "me'ẽ, pytyvõ",
            "apostar": "ha'ã, ñembosarái",
            "apoyar": "pytyvõ, mbojeko",
            "apreciar": "momba'e, hayhu",
            "aprendiz": "oikeramóva, oñepyrũva",
            "apresurar": "mbopya'e, mokyre'ỹ",
            "aprobar": "moneĩ, mboaje, momorã",
            "aprovechar": "poruporã, porukuaa",
            "aproximar": "mboja, moaguĩ",
            "apuñalar": "kutu, porokutu, kysekutu",
            "apuntalar": "joko, mbojetu'u",
            "apuntar": "moma'ẽ",
            "apurar": "mbopya'e, mbohetia'e",
            "aquí": "ápe, ko'ápe",
            "aquietar": "mombyta, mbopytu'u, mokiriĩ",
            "arañar": "karãi, hai, ñakarãi",
            "arar": "hyvykói, yvyjo'o, yvymbovo",
            "árbol": "yvyra, yvyrarakã",
            "archipiélago": "ypa'ũndy, ypa'ũaty",
            "archivar": "ñongatu, mohendaguã",
            "archivo": "ñongatuha, temiñongaturupa",
            "arcilla": "ñay'ũ, tujusỹi",
            "arder": "hendy, kái, jepota",
            "ardid": "pokarẽ, ñuhã",
            "ardor": "takuvo, tatapytu, tuguyraku",
            "arena": "yvyku'i",
            "arenga": "ñemoñe'ẽ, ñemoñe'ẽpohýi",
            "arete": "namichãi",
            "argel": "ay, pochy, ñaña",
            "argumentar": "roviauka, hechauka",
            "armadillo": "tatu",
            "aro": "ñamichãi, mba'eapu'a",
            "aroma": "tyakuã, tyakuãporã",
            "arraigar": "rapo, ñembohapo, mbohapo",
            "arrancar": "mondoro, hekýi, hapo'o",
            "arrasar": "moperõ, monandi, mbyai",
            "arrastrar": "mbotyryry, mopoñy",
            "arrendar": "poruka",
            "arriar": "mboguyjy",
            "arribar": "guahẽ, jupi, ñemboja",
            "arriero": "karia'y",
            "arrimar": "moaguĩ, mboja, mboypy",
            "arrodillar": "moñesũ",
            "arrojar": "mombo, poi, japichy",
            "arrollar": "mboapakua, mbyapu'a",
            "arroyo": "ysysry",
            "arrugar": "mocha'ĩ, moñyñýi, mokuruchĩ",
            "arte": "mba'apokuaa, katupyry, temiporã",
            "artería": "tuguyrape",
            "asado": "ka'ẽ, mbyichy",
            "asaltar": "rairõ, kaguai, monda",
            "asamblea": "amandaje, atyha",
            "ascensor": "jupiha",
            "asentir": "monei, mohe'ẽº, nei",
            "aseo": "poteko, tekoresãi",
            "aserrar": "yvyrakytĩ, kytĩ, mbovos",
            "asesor": "pytyvõhára, tekombo'ehára",
            "asir": "jepokói, japyhy, joko",
            "asistir": "ho, me, pytyvõ",
            "asma": "hu'uvai, pytuhẽasy",
            "asno": "mburika",
            "asociar": "moirũ, ñomoirũrã",
            "asomar": "apysẽ, akãsẽ",
            "áspero": "havara, korócho",
            "asta": "ýva",
            "astilla": "yvyraku'i, yvyrapehengue",
            "astro": "mbyja, jasy",
            "astucia": "katupyry, akãporã",
            "asueto": "pytu'u, pytu'uha",
            "asustar": "mondýi, mongyhyje, pytaryrýi",
            "atacar": "rairõ, taky, ndyry",
            "atajar": "joko, mombyta, jepytaso",
            "atajo": "tapembyky, jepiaha, tapekañymby",
            "atardecer": "ka'aruete",
            "atascar": "mopa'ã, pa'ã",
            "atender": "ñangareko, ma'ẽaguĩ",
            "aterrar": "mongyhyje, mbopy'atytýi",
            "aterrizar": "guyjy, pyrũ, yvyguejy",
            "atrás": "tapykuépe, takykue, atukupépe",
            "atravesar": "hasa, hasapa, hesyvõ",
            "aumentar": "mbohetave, mbotuicha",
            "aurora": "ko'ẽmbota, ko'ẽtĩ, ko'ẽju",
            "ausente": "pore'ỹ, oĩ'ỹva, ndaipóri",
            "autobús": "mba'yrumýi",
            "autonomía": "ijehguíva",
            "autor": "apohare, apohára, apoha",
            "autoridad": "mburuvicha, tendota",
            "autorizar": "mbojerovia, jokuái, moneĩ",
            "auxiliar": "pytyvõhára, oipytyva",
            "avalar": "mbojerovia",
            "avanzar": "motenonde, ñemotenonde",
            "avaro": "jopy, hakate'ỹva",
            "avasallar": "ñemomba'e, mbopoguy",
            "aventar": "mboveve, mombo",
            "averiar": "mbyai, ñembyai",
            "averiguar": "porandu, jeporeka, typeka",
            "avestruz": "ñandu, ñandu guasu, churi",
            "avión": "mba'yruveve",
            "avisar": "momarandu, ñatõi, kuaauka",
            "avispa": "káva, kavichu'i",
            "avistar": "hecha, hecha mombyry",
            "axila": "jyvaguy",
            "ayudar": "pytyvõ",
            "ayunar": "py'anandi, karu'i",
            "azar": "sapy'agua, ojehureíva",
            "azotar": "nupã, mbyepoti, havira",
            "azul": "hovy, chovy",
            "azuzar": "moñarõ, mbopochy, moñorairõ"
        
            // Agrega más traducciones aquí
        };

        return translationDatabase[text] || "No se encontró traducción";
    }
});
